title: Vala's Blog
description: >-
  Sharing my thoughts on open source, programming, and technology.
# theme: minima
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
plugins:
  - jekyll-feed
permalink: /:year/:month/:day/:title.html
